### Modulo per la configurazione delle dimensioni (SZ = Size)

SZ_window_w_ratio = 0.8
SZ_window_h_ratio = 0.8
SZ_min_window_w = 750
SZ_min_window_h = 500
SZ_topbar_h = 50
SZ_dialog_w = 750
SZ_dialog_h = 450
SZ_tbl_pat_list_row_h = 30 # altezza righe (tabella lista pazienti)
SZ_tbl_pat_hist_row_h = 40 # altezza righe (tabella storico paziente)
SZ_tbl_scroll_w = 18
SZ_btn_login = 30
SZ_logo_w = 300
SZ_logo_h = 100
SZ_bscan_preview_w = 300
SZ_bscan_preview_h = 200
SZ_bscan_preview_padx = 10
SZ_bscan_preview_pady = 10
SZ_bscan_dialog_w = 750
SZ_bscan_dialog_h = 450
SZ_bscan_dialog_min_w = 400
SZ_bscan_dialog_min_h = 300